---
title: "TODO dolka"
author: "Yves Deville"
date: "`r Sys.Date()`"
output:
  md_document:
    toc: true
    number_sections: true
---

This document is intended to be read from the generated html output
`TODO.html`. However wherever this output is not suitably rendered you
can read the mardown version `TODO.md` which seems correct up to some
problems for math.
	
# General

- The one-point optimization criteria such as \code{"EI"} and their
  derivatives could optionnaly be computed by the \code{predict}
  method or by a new method say \code{optCrit1}.


# Existing functions

- `contours` Allow to pass further arguments to `predict` or to the
functions `other` and `otherGrad`. For instance we may want to change
`type` in `predict` or `proxy` in `EI` used as `other`.

- **[x]** `genoud_cache` Check that all arguments of `fn` are well
  used. Of course, optimization criteria such as `EI` needs `model`.

# New functions

- Add a `optim_cache` function to use `optim` without having to
manually cache the gradient in an environment.
